language: node_js
node_js:
- stable
install:
- npm install
script:
- npm run test
after_success:
- npm run coveralls
deploy:
  provider: lambda
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  function_name: martinServer
  region: eu-west-2
  handler_name: handler
  runtime: nodejs6.10
  publish: true
  zip: deploy.zip
  role: "$ROLE"
  on:
    all_branches: true
before_deploy:
- zip -r deploy.zip index.js package.json node_modules/
after_deploy:
- unzip -l deploy.zip
env:
  global:
  - secure: dCvUrqDMIVhZzJ1Ef1YYWXMZNZh8r3Pi79spD/lJ7UTT5jXXiDvTgCrOJVobaI3eYXQjVgVchVPtiGMN9+XC2ZUZXOkA7ztnWox2HK7WaeozXJRvBzb4lE9JBLTtWkiPsekSt2IVjUJFGNPnL6XzeYrPiqHdSs6+GYvVL+6ndemMG0SdjJZDU17OkbPwsLXFd4izoD2P4UeL03efezfJ4F3u9yAp6amlFXjS1OoZSrxyESokWAPtM+1KnvyCmO3JUqraVCHvv6BXZHRbJcZ/m0ILibdx3CCN0DuAmAcpMXO6SiEN1BEkXeHkdXgYYsRNStXzinx0ExJ835xz6b0EcUigg8WPVOT1q6Tz+2tFrdvOwmEBSN4IcrqUPRNLy54HgA9jgRH8dQEkkEoRxOtFSapijH4rtzAywU0JyTZjbdXIq7Nzq2CL9yr83WHI3KO2jYgqmLSvV87XrpJnMI3tFccEsm2CYqi+d1jgFGoenKBV07JSuR5zsmSzBhpENlFkTlNjWiM4+Gty5R7rO1VG7lPhXdpdzGHPcEh/NTyJHmnPuM7AsjrFGv+ubRUoIgsCvfv/oH5qO/UtsAzU5xnEEeINanirclEhbuZnMM43HQWEZZhd26aKY5ryHWHxxIZMA+GNAYFHwOaSs6fBn/6K7VffIrWqJQQBj0+fqDGbaWs=
  - secure: e5Yn6weZEwUKeXtTv9BXgaZXvuFYWxx7/kbvtkQDZHTedoS32wS6PkYp0m5fSHgAeGomy3Z0Of4PTq8KICQqa7qVYzS6a4csHOAiQIqT7dpi9XbnFQbc9539aEbWfOQcpccj42m9/e0ji8qIivcq6xiRTYRj1FSrybzM4U0kJjW8tCwnROKFLkOOKMHi/8waQau0MuodBfK28pt390oneHrG0f1CuEaxHEk9qaouSikY2h1QPqHFLzjNcBYsGJe7RBPWVbIqlw3u0Ncb6yXyiEUpC1/noqwEAdrG22+vDLOrYLgoPeG48utAkZ3TmUNs6n5T/HSmwZJMYlXPilrNQSnNQmvZWJCtYOA2mhBMhxMM7mCeYTeTcIZpkbi75/EjTCXQRuBV3T3e14FG+urwBBnImKpmqA72lOPcIFqRCPDRT2RfN4bPZLcb5jYgfFXQ6bKYa0FC/qtQb0Cs2Gr8+KGYZM1EhlZFBPElP+feJ5ie9A+RNCEkRwygMQJffctrBRjNR/e2wS1NjfkNQD6ygCd/2jYNbMY7otsif3KrzQb8yCLAmLGO/hXnFBfYYiAW6Do591NaHPlJySSeUy42PAopEBfSncOU3edrhfhZFDb2dvUjqz1LPRgwLUzQzabbXpa9xdOqmeWi/MvZAI/LLxZQkDvNDhJp/QX6R99T8vc=
  - secure: H2nN5a8tcDNMjlgEcP2fKkeCpdJ2DPKeLHuLu0rGWDTvtsK/xuPUStXWfgnA4rFMRnvOFiUtnIXbgtGZ6amx5EsgfJmR0dtPnEZtuvVN9bWlraIeUvwlu1ZmdPj6xdveziE5DvISAQwUTp9uPbNWZtaph8Ad6ifGfK4lXlBHrO98eCjAIgOQi3UfGrgOs0GSAg2MwUNQwlroJeFciLrYnfaDBLSb8CihTnYvQeSfO1cZx4fjh4NbJdiQfiXtscfvQxGkP+EQ0hUCUSHZHX6TnAExy1kg78sx0Jac5DyO0BwKCTlq3tOEvPlmvif3ULDY9PoHmj9MQvoZAB0vURW2+J3vwFo2qocrnRYF7r40WbS1mnMgvaIEnS3YICK1e9litl0U42M6I+ho+GNoCbg6sjKdm9K4urnIrRDMNh4dwV1C5HCe99U9kZ/hICyGbCeggPQrsATRh/QNjnTgP+HKvN/YJV3B9SQj1bVL4AsxicBbhKLIeqanCrXAeG8+0EaAkub1oogXfGT31kIe331eA/trkZFEomAwiwIFP49UPTjeV3AjGdRMSgy4yA8dw15cY9+4tp7mKMnqIrPxMgbJ/nR99KQl/w/W+gFQbVEIcSmAaivXSg0hgLED7ehfVpFAygiCQ3eaZoMnKt9PF2YcDi66oS1VmgCUYSzts3fjlYg=
